app:
  title: C++ In-class Lab 3 - Functions & Recursion
  description: 這次的 C++ 的函數 (Functions) 與遞迴 (Recursion)：函數宣告與定義、參數傳遞、遞迴呼叫。
compiler_path: "g++"
problems:
  p1:
    name: 高塔建築師 (The Tower Architect)
    points: 20
    timeout: 1
    forbidden:
    - for
    - while
    - do
    - goto
    required:
    - factorial
    - sum
  p2:
    name: 完美鋪磚計畫 (The Perfect Tiling Project)
    points: 20
    timeout: 1
    forbidden:
    - for
    - while
    - do
    - goto
    required:
    - gcd
  p3:
    name: 破解數學家的謎題 (Cracking the Mathematician's Puzzle)
    points: 30
    timeout: 1
    required:
    - isPrime
  p4:
    name: 遞迴的足跡 (Footsteps of Recursion) 
    points: 30
    timeout: 1
    required:
    - fib
  p5:
    name: 受詛咒的直線 (The Cursed Line) - Bonus
    points: 20
    timeout: 1
    forbidden:
    - for
    - while
    - do
    - goto
    required:
    - hanoi

defaults:
  timeout: 1
